---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.9.11
    chart: loki-stack
    helm:
      values: |
        promtail:
          enabled: false
        fluent-bit:
          enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
