---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 6.1.0
    helm:
      releaseName: argocd
      values: |
        configs:
          cm:
            url: https://argo.cloudnativerioja.com
            admin.enabled: false
            # Dex configuration
            dex.config: |
              connectors:
                # GitHub example
                - type: github
                  id: github
                  name: GitHub
                  config:
                    clientID: $sso-secret:clientID
                    clientSecret: $sso-secret:clientSecret
                    orgs:
                    - name: cloudnativerioja
              staticClients:
                - id: argo-workflows-sso
                  name: Argo Workflow
                  redirectURIs:
                    - https://workflows.cloudnativerioja.com/oauth2/callback
                  secretEnv: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
          rbac:
            policy.default: role:readonly
            policy.csv: |
              p, role:org-admin, applications, *, */*, allow
              p, role:org-admin, clusters, get, *, allow
              p, role:org-admin, repositories, get, *, allow
              p, role:org-admin, repositories, create, *, allow
              p, role:org-admin, repositories, update, *, allow
              p, role:org-admin, repositories, delete, *, allow
              p, role:org-admin, logs, get, *, allow
              p, role:org-admin, exec, create, */*, allow

              g, cloudnativerioja:Organizers, role:org-admin

          params:
            server.insecure: true
        server:
          ingress:
            # -- Enable an ingress resource for the Argo CD server
            enabled: true
            # -- Additional ingress annotations
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
              kubernetes.io/ingress.class: traefik
              traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
              traefik.ingress.kubernetes.io/router.tls: "true"
            # -- Additional ingress labels
            labels: {}
            # -- Defines which ingress controller will implement the resource
            ingressClassName: ""
            hosts:
              - argo.cloudnativerioja.com
              # - argocd.example.com
            # -- List of ingress paths
            paths:
              - /
            # -- Ingress path type.
            pathType: Prefix
            # -- Additional ingress paths
            extraPaths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: argocd-server
                    port:
                      number: 443
            # -- Ingress TLS configuration
            tls:
              - hosts:
                  - argo.cloudnativerioja.com
                secretName: tls-argo-cloudnativerioja-com
            https: false
        dex:
          env:
            - name: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sso-secret
                  key: clientSecret
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
