---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
  source:
    chart: argo-rollouts
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 2.34.0
    helm:
      values: |
        dashboard:
          # -- Deploy dashboard server
          enabled: true
          # -- Set cluster role to readonly
          readonly: true
          ingress:
            # -- Enable dashboard ingress support
            enabled: true
            # -- Dashboard ingress annotations
            annotations: 
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
              kubernetes.io/ingress.class: traefik
              traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
              traefik.ingress.kubernetes.io/router.tls: "true"
            # -- Dashboard ingress labels
            labels: {}
            # -- Dashboard ingress class name
            ingressClassName: ""

            # -- Dashboard ingress hosts
            ## Argo Rollouts Dashboard Ingress.
            ## Hostnames must be provided if Ingress is enabled.
            ## Secrets must be manually created in the namespace
            hosts: 
              - rollouts.cloudnativerioja.com
            # -- Dashboard ingress paths
            paths:
              - /
            # -- Dashboard ingress path type
            pathType: Prefix
            tls: 
              - hosts: 
                  - rollouts.cloudnativerioja.com
                secretName: rollouts-tls
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
