apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-key
  namespace: argocd
spec:
  encryptedData:
    api-key: AgCRNCIbZIy3/GVhN8UYQ2aaSi+qaEBaGpABbt8yexuBqmCwi2ZtO4WOyTCfN+0a0VPw9q1VdUZHFpFFHKM2u2MecoOQxZCd8v614Ofm4tWSsUj5cWwSXhakLcAkRPQ59Ag++8VuCyBrnmWlOXOpo1QPx7xG5p1BhQ1WUWygUQ1iOie3JsBoVR5PIgYWfF2yqmsQtRo1GtZS/9Ooscb2r9v+UWXlS3exkKskUbaa2mkxgWglmwzA2rnkiBylVKmhgBi3cNdbMh3bu0H8FLav8rj4EQQivjsip1S4oZZ9RUh/z5nmCR3liaZsFsyT/GkZB1mb6nFMTKmBeMg/NasjTEZpcf0IKLAnq+cygKwOfFW3lhdQrecUzaYg6aZrG3HI0K0AAoScwX79XvTOqtUD8vT+LmNBLt7QTLiTp0kxGMpk3rpf/+G2C1HwU5DZW1aPcBtj7XH5D3+VBpOMMzY8yFf2hKhleyiS4V+aH9/+MsQ0UId2G0mk9fZJHcdXHTjZqVQ1CgvcUa+dlNxFdgVsfJePOm4APteYVQUHAWuVAusgEICAdL2M1HF1bLatXX3CV7N0jjQZ3GBtBA5a9K4en5FUrIoEa155qlBpcmylj6WWU52ekVyPif4W5ZEFrLW5ANRzI6GW2i9KPXrcByhAQTh6mvNDRZORGazvpUUNzck4To7sE3yOPjI0IQCNfx0TEqDLJW8/k9dpDF24nmFA5JeJ+1uaKhHCNK7NuQvwI2F9Elax3a8/9C1u # yamllint disable-line rule: line-length
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-key
      namespace: argocd
