apiVersion: v1
kind: Service
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  labels:
    name: cluster-autoscaler
  annotations:
    prometheus.io/scrape: "true"
spec:
  ports:
    - name: http
      port: 8085
      targetPort: app
  selector:
    app: cluster-autoscaler
