apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-labels
  annotations:
    policies.kyverno.io/title: Add Labels
    policies.kyverno.io/category: Sample
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Label
    policies.kyverno.io/description: This policy performs a simple mutation which adds a label # yamllint disable-line rule:line-length
spec:
  background: false
  rules:
    - name: add-labels
      match:
        any:
          - resources:
              kinds:
                - Pod
                - Service
                - ConfigMap
                - Secret
      mutate:
        patchStrategicMerge:
          metadata:
            labels:
              CNCF-community-group: Cloud-Native-Rioja
