apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-labels
  annotations:
    policies.kyverno.io/title: Add Labels
    policies.kyverno.io/category: Sample
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Label
    policies.kyverno.io/description: >-
# yamllint disable-line rule:line-length
      Labels are used as an important source of metadata describing objects in various ways
      or triggering other functionality. Labels are also a very basic concept and should be
      used throughout Kubernetes. This policy performs a simple mutation which adds a label
      `CNCF-community-group: Cloud-Native-Rioja` to Pods, Services, ConfigMaps, and Secrets.
spec:
  background: false
  rules:
    - name: add-labels
      match:
        any:
          - resources:
              kinds:
                - Pod
                - Service
                - ConfigMap
                - Secret
      mutate:
        patchStrategicMerge:
          metadata:
            labels:
              CNCF-community-group: Cloud-Native-Rioja
