---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: 23.2.0
    helm:
      releaseName: traefik
      values: |
        deployment:
          kind: DaemonSet
        api:
          dashboard: true
          insecure: true
        logs:
          general:
            level: DEBUG
  destination:
    server: "https://kubernetes.default.svc"
    namespace: core-apps
