---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: 23.2.0
    helm:
      releaseName: traefik
      values: |
        deployment:
          kind: DaemonSet
        api:
          dashboard: true
          insecure: true
        logs:
          general:
            level: INFO
        providers:
          kubernetesCRD:
            # -- Load Kubernetes IngressRoute provider
            enabled: true
            allowCrossNamespace: true
            # -- Allows to reference ExternalName services in IngressRoute
            allowExternalNameServices: true
            # -- Allows to return 503 when there is no endpoints available
            allowEmptyServices: true
            # ingressClass: traefik-internal
            # labelSelector: environment=production,method=traefik
            namespaces: []
              # - "default"

          kubernetesIngress:
            # -- Load Kubernetes IngressRoute provider
            enabled: true
            # -- Allows to reference ExternalName services in Ingress
            allowExternalNameServices: true
            # -- Allows to return 503 when there is no endpoints available
            allowEmptyServices: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: core-apps
