---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
  source:
    chart: minio
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.8.12
    helm:
      releaseName: minio
      values: |
        auth:
          existingSecret: minio-credentials
        ingress:
          enabled: true
          hostname: minio.cloudnativerioja.com
          ## @param ingress.path The Path to MinIO&reg;. You may need to set this to '/*' in order to use this with ALB ingress controllers.
          ##
          path: /
          pathType: ImplementationSpecific
          servicePort: minio-console
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            kubernetes.io/ingress.class: traefik
            traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
            traefik.ingress.kubernetes.io/router.tls: "true"
          tls: true
          selfSigned: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: core-apps
