---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
  source:
    repoURL: https://opensearch-project.github.io/helm-charts/
    targetRevision: 2.14.1
    chart: opensearch
    helm:
      values: |
        singleNode: true
        resources:
          limits:
            cpu: 512m
            memory: 2Gi
          requests:
            cpu: 512m
            memory: 1Gi
        securityConfig:
          internalUsersSecret: internal-users
        extraEnvs:
          - name: DISABLE_INSTALL_DEMO_CONFIG
            value: "true"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
