apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-key
spec:
  encryptedData:
    api-key: AgBBwi6rNtOkQ8aLNhx8e6iuB6i1fyW2JC38xqeOBShWmbNARaE98V9vATPzNEw8QjiO/kEHlFwe8kBQUyMSb4UsHyzDZUvN9lnhJMQ6SGcV7VIx79fJBY9ogz7zkkg5FRwF7nLy+/xwJwp5CuaxpREBXuf7w0TC7/ztbL3t2lBKUMFx/AU+ykXAkDha1Nc2lczWC9mmMuoOLnojCd1KsPEgfnJuIcwG65ZxhC6VCZIQ4TeBMZV5M0yVdqy42jFb1+u4VuRiCICS5riridyHsQVwHdhv+geQng7juvJYctGxnjmQVVrkeCXhGJiCaTOfn+z27qRiQ2XTqFi0R8FI+WokeUS3iqg0V76HZaVkhJy4Ddxq+3rDbdiAOmGE4k/qhHuE5G5AnYjDgr804xm+Ioyltya1FdsdjhKPXNc15VOavbYuSvj4nU6mg/1rxHwY+3eq5TXtXdx23nsZ+nrH2UO/0MSOMdHam/ZOB7IDfIJBhi3Gh/JXqnwPVS1/qL/+7NixkFc977I5rwDDSb47TlW94PIicFplNFzQMjtYfOLPxKOvZ1UlujIpdUHcWfrOiTTrD3qnTql1hfhl1JqEM59J+nK8/x0LUxR8jfG1jn9ZF0RMVbMDMfIYOgEWq1Nga05Qpar8e5nSIyxGlPPpHvJHF8WMQWWQn4PyCa/1PYeOC/AaPLHwVMqiUKq2uPUDOGu/4vejTcAKDkpBMyEcuXYYhj23bSUWuUfxLw5zxhUGxvS9n70kFrgI # yamllint disable-line rule:line-length
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-key
