---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 5.39.0
    helm:
      releaseName: argocd
      values: |
        server:
          ingress:
            # -- Enable an ingress resource for the Argo CD server
            enabled: true
            # -- Additional ingress annotations
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
              kubernetes.io/ingress.class: traefik
              traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
              traefik.ingress.kubernetes.io/router.tls: "true"
            # -- Additional ingress labels
            labels: {}
            # -- Defines which ingress controller will implement the resource
            ingressClassName: ""
            hosts:
              - argo.cloudnativerioja.com
              # - argocd.example.com
            # -- List of ingress paths
            paths:
              - /
            # -- Ingress path type.
            pathType: Prefix
            # -- Additional ingress paths
            extraPaths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: argocd-server
                    port:
                      number: 443
            # -- Ingress TLS configuration
            tls:
              - hosts:
                  - argo.cloudnativerioja.com
                secretName: tls-argo-cloudnativerioja-com
            https: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
