---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 5.39.0
    helm:
      releaseName: argocd
      values: |
        ## Server
        server:
          service:
            type: LoadBalancer
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
