apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
spec:
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kyverno
    repoURL: https://kyverno.github.io/kyverno
    targetRevision: 2.6.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    helm:
      values: |
        grafana:
          # -- Enable grafana dashboard creation.
          enabled: true

          # -- Configmap name template.
          configMapName: '{{ include "kyverno.fullname" . }}-grafana'

          # -- (string) Namespace to create the grafana dashboard configmap.
          # If not set, it will be created in the same namespace where the chart is deployed.
          namespace: monitoring

          # -- Grafana dashboard configmap annotations.
          annotations: {}

          # -- Grafana dashboard configmap labels
          labels:
            grafana_dashboard: "1"

          # -- create GrafanaDashboard custom resource referencing to the configMap.
          # according to https://grafana-operator.github.io/grafana-operator/docs/examples/dashboard_from_configmap/readme/
          grafanaDashboard:
            create: true
            matchLabels:
              dashboards: "grafana"
