apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: sso-secret
  namespace: argocd
spec:
  encryptedData:
    dex.github.clientSecret: AgAaQ6ectjbhaoSo2KXx8qH9UXf5i5vHlLUOcvTehW3dY5qEmHSaAN7d76SCM0sIqiCUmbUpVrFXypEhjFU1GKAtfNaVT0tMpe3RH6JcEGBh4jz71BOm5KR+IjFj7FnJdBrwP0BMzs1suSccDF78kZaKVcjVvMD6fkjKMTs2m5kr81UVz8x1FgoTO9MW94rQ1p5U/XKFWbjkOaOVTVXXlfg063j6TfD815nQ5FSYMBDTIbjzNgb6aIEqZqWDfOuOi7QWOCTQPriceWp6zVjU39J2EvYpCkonob1vlSYou+QRrE5A89XQa6+d8yBbYJ18N84bR7zZIwTRSBNSCaBTpSXpMU73/nZJKVJUuW0hF1jeFQp4Kn5wFvzKuk6rDfX9Cjp4bkuGgnV4ovJed4sJIqyoZRd64f4/rHLfvRBQNIkYkiro8bzf9T7qyR7ma0ikJbR0DTx504B23CUYVSOTq8CEztfQGHM4WnS02RtVDAzafS0U7ItwrJ0m2YlkSLCQ/MuMTm5wBf/hueYAlz2O20o+fuBgHDBSncbUkfcxnX8vaA+BL3gnR4QeEdVpgByAv/2zLCtxjbmbSq9F5nuIaUkeTdJaP8H/+HeMtBL6I/zdACnyOIpGNSselIu20zx4wINtxb0FveesCVX9X+EigsRAthCNTUZbaTnPnoxvmn9RfELntF5ckF3dY9yPtJy2RINx+guimbM9aDWQdokwSe8IE5QnBZw9/OmodKOe0a/J7sekkFqrqtR9kA== # yamllint disable-line rule:line-length
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: sso-secret
      namespace: argocd
