apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: sso-secret
  namespace: argocd
spec:
  encryptedData:
    dex.github.clientSecret: AgCnohepUb8ra7DrfYaIpcmM4yy2MWkrul35too4UGPRvK0LeOY72Drl/jtZl7Ruqg7q5pF0IAswwgtgEtFOqo9s2shQsx5FBe3AbywF3v+l3LXqUSobEeagZpffwDCohIA2pfJdE21V01Un6CkqtOmqcvCfBlL4MySYRsCAm8NQFTlsrBA06K++K//TIr8psdz5XDp1Kz10bS+MeT7guVHM8M5ZNfK1AOYW17aQ5uzzaS3VgZgCWFdENyd75tnUNKT6ZvjssafHZBeuXTbTbd//CvPvcMGAHyH8yo5q8AYFnfXQiLs0t6ntnjx2em6Pu1sCY9hEFILeifmIwZw/mzDusrAYX585BKWSidykBqEY4Hr5PlRw7ch6a1cZB0QI3TUsiJDZFEXtgJvLKxi1+fdLkXZquHez8Ak4GuyZ0ILCOePa1Cfk1gtTP0uvgySjKyjkhfK9gqmYttBwbpIkBmw8ULgRs1Jo3labHTPENhhyGmOSuHXvLQxFamls9AyKGKoVSn2jWCJMqLRLVl17HC43GR7XDOZwR+DgHMyc955/iu5lDs9dtdE6gv6wII+vOonDQfqs0gMk+7Spl6z3d6dF/Ft7gJ7qdJTPj/6leBr23qzh8kQF8ErvwedeQwYhQJAP+nzjygJOisIjs2TB1t3VsE22oXsz1tGm1VO0mcpKalxY7PomqdxkUKxmVP4wUpJhFaJBsM/1MoHdsN4FktBzwTSzbRCyiWcdIV74L0w7sLz/fuxEkcyv # yamllint disable-line rule:line-length
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: sso-secret
      namespace: argocd
