apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 48.4.0
    chart: kube-prometheus-stack
  destination:
    server: "https://kubernetes.default.svc"
    namespace: core-apps
