---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 8.18.0
    chart: kube-prometheus
    helm:
      values: |
        prometheus:
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 256m
              memory: 1Gi
          additionalScrapeConfigs
            enabled: true
            type: internal
            jobList:
              - job_name: 'kyverno-collector'
                # metrics_path defaults to '/metrics'
                # scheme defaults to 'http'.
                static_configs:
                  - targets: ['kyverno-metrics.kyverno.svc.cluster.local:8000']
        blackboxExporter:
          enabled: false
        exporters:
          kube-state-metrics:
            enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
